blank_issues_enabled: false
contact_links:
  - name: Don't have a GitHub account? Not familiar with GitHub?
    url: https://50l.cc/gugu-qgroup
    about: Click the button on the right to join the QQ group for feedback
